apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy
  namespace: openshift-migration-toolkit
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
